# Generated by Django 3.2.9 on 2022-01-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
